// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5wa4tP8dwGB34HMaV1vr4sFa20AuDGSc',
    appId: '1:128329347435:android:d97340369b562827c21c2e',
    messagingSenderId: '128329347435',
    projectId: 'testing-ppb-a0260',
    storageBucket: 'testing-ppb-a0260.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2pilVCORnTNiBbn_LxDKXINB_wfzB9tY',
    appId: '1:128329347435:ios:86ca599981d45185c21c2e',
    messagingSenderId: '128329347435',
    projectId: 'testing-ppb-a0260',
    storageBucket: 'testing-ppb-a0260.firebasestorage.app',
    iosBundleId: 't',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2pilVCORnTNiBbn_LxDKXINB_wfzB9tY',
    appId: '1:128329347435:ios:2d2f43424d8c959cc21c2e',
    messagingSenderId: '128329347435',
    projectId: 'testing-ppb-a0260',
    storageBucket: 'testing-ppb-a0260.firebasestorage.app',
    iosBundleId: 'flutt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm9OrFxCe_Ez-Fk0W5uaOMrChnTCB0XJw',
    appId: '1:128329347435:web:4262bde591345e02c21c2e',
    messagingSenderId: '128329347435',
    projectId: 'testing-ppb-a0260',
    authDomain: 'testing-ppb-a0260.firebaseapp.com',
    storageBucket: 'testing-ppb-a0260.firebasestorage.app',
    measurementId: 'G-LDZ5VDGQHQ',
  );
}
